apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moviedb
  namespace: apollo11
spec:
  selector:
    matchLabels:
      app: moviedb
  serviceName: "moviedb"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: moviedb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: moviedb
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: moviedb
        volumeMounts:
        - name: moviedb
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: moviedb
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moviedb
              key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: moviedb
          persistentVolumeClaim:
            claimName: moviedb