apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookingdb
  namespace: apollo11
spec:
  selector:
    matchLabels:
      app: bookingdb
  serviceName: "bookingdb"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: bookingdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bookingdb
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: bookingdb
        volumeMounts:
        - name: bookingdb
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookingdb
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bookingdb
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: bookingdb
              key: POSTGRES_DB
      volumes:
        - name: bookingdb
          persistentVolumeClaim:
            claimName: bookingdb