apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification
  namespace: apollo-observability
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: apollo-airlines
    release: apollo11
spec:
  selector:
    matchLabels:
      app: notification
  namespaceSelector:
    matchNames:
      - apollo-airlines-apps
  endpoints:
    - port: 8084
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  jobLabel: app
