apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-airlines-config
  namespace: apollo-airlines-apps
data:
  PORT_IDENTITY: "8080"
  PORT_FLIGHT: "8081"
  PORT_BOOKING: "8082"
  PORT_SEARCH: "8083"
  PORT_NOTIFICATION: "8084"
  PORT_FRONTEND: "3000"

  IDENTITY_DB: "identity"
  FLIGHT_DB: "flight"
  BOOKING_DB: "booking"

  VITE_IDENTITY_URL: "http://identity.apollo-airlines-apps.svc.cluster.local:8080"
  VITE_FLIGHT_URL: "http://flight.apollo-airlines-apps.svc.cluster.local:8081"
  VITE_BOOKING_URL: "http://booking.apollo-airlines-apps.svc.cluster.local:8082"
  VITE_SEARCH_URL: "http://search.apollo-airlines-apps.svc.cluster.local:8083"

  IDENTITY_SERVICE_URL: "http://identity.apollo-airlines-apps.svc.cluster.local:8080"
  FLIGHT_SERVICE_URL: "http://flight.apollo-airlines-apps.svc.cluster.local:8081"
  NOTIFICATION_SERVICE_URL: "http://notification.apollo-airlines-apps.svc.cluster.local:8084"

  REDIS_URL: "redis://redis.apollo-airlines-infra.svc.cluster.local:6379"
  DATABASE_URL_TEMPLATE: "postgresql://postgres:postgres@{{host}}:5432/{{db}}"
  IDENTITY_DB_URL: "postgresql://postgres:postgres@identity-db.apollo-airlines-infra.svc.cluster.local:5432/identity"
  FLIGHT_DB_URL: "postgresql://postgres:postgres@flight-db.apollo-airlines-infra.svc.cluster.local:5432/flight"
  BOOKING_DB_URL: "postgresql://postgres:postgres@booking-db.apollo-airlines-infra.svc.cluster.local:5432/booking"