apiVersion: v1
kind: Secret
metadata:
  name: apollo11-secrets
  namespace: apollo11-apps
type: Opaque
stringData:
  # DB passwords (dev only — use sealed-secrets/vault in production)
  POSTGRES_PASSWORD: "postgres"

  # JWT secret (dev only — use external secret store in production)
  JWT_SECRET: "apollo11-dev-secret-change-in-production"
