apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentdb
  namespace: apollo11
  labels:
    app: paymentdb
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-pd-standard-rwo-sc
  resources: 
    requests:
      storage: 300Mi