apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunar-postgres
  name: lunar-postgres
  namespace: apollo11
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: lunar-postgres
