apiVersion: v1
kind: Service
metadata:
  labels:
    app: theatre
  name: theatre
  namespace: apollo11
spec:
  ports:
    - name: theatre
      port: 7000
      targetPort: 7000
  selector:
    app: theatre
