apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunar-app
  name: lunar-app
  namespace: apollo11
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lunar-app