apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-infra
  labels:
    app.kubernetes.io/name: apollo11-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-apps
  labels:
    app.kubernetes.io/name: apollo11-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-ui
  labels:
    app.kubernetes.io/name: apollo11-ui
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
  labels:
    app.kubernetes.io/name: chaos-mesh
