apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  labels:
    app: payment
  name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: apollo11-payment:working
          name: payment
          imagePullPolicy: Never
          startupProbe:
            httpGet:
              path: /started
              port: 8000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            successThreshold: 5
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: payment
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: payment
                  key: DATABASE_NAME
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: payment
                  key: DATABASE_PORT
            - name: DATABASE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: payment
                  key: DATABASE_USER_NAME
            - name: DATABASE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: payment
                  key: DATABASE_USER_PWD
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
