apiVersion: v1
kind: Service
metadata:
  labels:
    app: booking
  name: booking
  namespace: apollo11
spec:
  ports:
    - name: booking
      port: 3000
      targetPort: 3000
  selector:
    app: booking