apiVersion: v1
kind: Service
metadata:
  name: theatredb
  namespace: apollo11
  labels:
    app: theatredb
spec:
  ports:
  - port: 27017
    name: theatredb
  clusterIP: None
  selector:
    app: theatredb