apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo11-config
  namespace: apollo11-apps
data:
  SERVICE_PORT: "8080"
  DATABASE_HOST: "identity-db.apollo11-infra.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "identity_db"
  REDIS_HOST: "redis.apollo11-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  VITE_IDENTITY_URL: "http://identity.apollo11-apps.svc.cluster.local:8080"
  VITE_FLIGHT_URL: "http://flight.apollo11-apps.svc.cluster.local:8081"
  VITE_BOOKING_URL: "http://booking.apollo11-apps.svc.cluster.local:8082"
  VITE_SEARCH_URL: "http://search.apollo11-apps.svc.cluster.local:8083"
