apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo11-config
  namespace: apollo11-apps
data:
  PORT_IDENTITY: "8080"
  PORT_FLIGHT: "8081"
  PORT_BOOKING: "8082"
  PORT_SEARCH: "8083"
  PORT_NOTIFICATION: "8084"
  PORT_FRONTEND: "3000"

  VITE_IDENTITY_URL: "http://identity.apollo11-apps.svc.cluster.local:8080"
  VITE_FLIGHT_URL: "http://flight.apollo11-apps.svc.cluster.local:8081"
  VITE_BOOKING_URL: "http://booking.apollo11-apps.svc.cluster.local:8082"
  VITE_SEARCH_URL: "http://search.apollo11-apps.svc.cluster.local:8083"

  IDENTITY_SERVICE_URL: "http://identity.apollo11-apps.svc.cluster.local:8080"
  FLIGHT_SERVICE_URL: "http://flight.apollo11-apps.svc.cluster.local:8081"
  NOTIFICATION_SERVICE_URL: "http://notification.apollo11-apps.svc.cluster.local:8084"
  SEARCH_SERVICE_URL: "http://search.apollo11-apps.svc.cluster.local:8083"
  BOOKING_SERVICE_URL: "http://booking.apollo11-apps.svc.cluster.local:8082"

  REDIS_URL: "redis://redis.apollo11-infra.svc.cluster.local:6379"
  IDENTITY_DB_URL: "postgresql://postgres:postgres@identity-db.apollo11-infra.svc.cluster.local:5432/identity"
  FLIGHT_DB_URL: "postgresql://postgres:postgres@flight-db.apollo11-infra.svc.cluster.local:5432/flight"
  BOOKING_DB_URL: "postgresql://postgres:postgres@booking-db.apollo11-infra.svc.cluster.local:5432/booking"