apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: apollo11
  name: theatredb
  labels:
    app: theatredb
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-pd-standard-rwo-sc
  resources: 
    requests:
      storage: 300Mi
