apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentdb
  namespace: apollo11
  labels:
    app: paymentdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi