apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: apollo11

resources:
  - config/kustomization.yaml
  - infra/postgres/kustomization.yaml
  - infra/redis/kustomization.yaml
  - apps/auth/kustomization.yaml
  - apps/catalog/kustomization.yaml
  - apps/circulation/kustomization.yaml
  - apps/notification/kustomization.yaml
  - apps/fines/kustomization.yaml
  - apps/frontend/kustomization.yaml
  - jobs/kustomization.yaml