apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  labels:
    app: pgadmin
type: Opaque
data:  
  pgpass: |
      cG9zdGdyZXMtMC5wb3N0Z3Jlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzI6Kjpwb3N0Z3Jlczpwb3N0Z3Jlcwo=
