apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timeline-mongodb
  name: timeline-mongodb
  namespace: apollo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline-mongodb
  template:
    metadata:
      labels:
        app: timeline-mongodb
    spec:
      containers:
      - image: mongo:latest
        name: liftoff-timeline-mongodb
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        - name: MONGO_INITDB_DATABASE
          value: "timeline"
        command: ["mongod", "--auth"]
        ports:
        - containerPort: 27017
          name: timeline-mongo
        volumeMounts:
        - name: timeline-mongodb-data
          mountPath: /data/db
        - name: init-mongo-js
          mountPath: /docker-entrypoint-initdb.d/init-mongo.js
      volumes:
        - name: timeline-mongodb-data
          emptyDir: {}
        - name: init-mongo-js
          hostPath:
            path: /etc/init-mongo.js
            type: File