apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  labels:
    app: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB_PASSWORD: postgres
