# loki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      volumes:
        - name: loki-cm
          configMap:
            name: loki
        - name: loki-pvc
          persistentVolumeClaim:
            claimName: loki
      containers:
        - name: loki
          image: grafana/loki
          args:
            - "--config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-cm
              mountPath: /etc/loki/
            - name: loki-pvc
              mountPath: /loki/