apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lunar-app
  name: lunar-app
  namespace: apollo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lunar-app
  template:
    metadata:
      labels:
        app: lunar-app
    spec:
      nodeName: apollo-worker2
      containers:
      - image: liftoff-lunar-app
        name: liftoff-lunar-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: lunar-app
        env:
        - name: DB_HOST
          value: "lunar-postgres.apollo11.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "lunar"

          