apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flight-db
  namespace: apollo-airlines-infra
spec:
  serviceName: flight-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: flight-db
  template:
    metadata:
      labels:
        app: flight-db
    spec:
      serviceAccountName: apollo11-infra
      initContainers:
        - name: init
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h flight-db -U postgres; do sleep 2; done
              psql -h flight-db -U postgres -d flight -f /init/init.sql || true
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: apollo-airlines-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /init
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apollo-airlines-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "flight"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "flight"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "flight"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-script
          configMap:
            name: flight-db-init-script
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi