apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-infra
  labels:
    app.kubernetes.io/name: apollo11
    app.kubernetes.io/component: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-apps
  labels:
    app.kubernetes.io/name: apollo11
    app.kubernetes.io/component: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: apollo11-ui
  labels:
    app.kubernetes.io/name: apollo11
    app.kubernetes.io/component: ui