apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fines-allow-specific
  namespace: apollo11-apps
spec:
  podSelector:
    matchLabels:
      app: fines
  policyTypes:
    - Ingress
  ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: apollo11-ui
            podSelector:
              matchLabels:
                app: frontend
