{{- /*
Base overlay — common resources for all environments
*/ -}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apollo11

commonLabels:
  app.kubernetes.io/name: apollo11

resources:
  - ../base/helm/apollo11

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: identity
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: identity
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flight
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: flight
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: booking
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: booking
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: search
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: search
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: notification
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: frontend