apiVersion: v1
kind: Service
metadata:
  labels:
    app: telemetry-app
  name: telemetry-app
  namespace: apollo11
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: telemetry-app