apiVersion: v1
kind: Service
metadata:
  name: booking-db-headless
  namespace: apollo-airlines-apps
spec:
  clusterIP: None
  selector:
    app: booking-db
  ports:
    - port: 5432
      targetPort: 5432
