apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: bookinginit
  namespace: apollo11
data:
  create.sql: |-
    CREATE TABLE IF NOT EXISTS bookings (
      id SERIAL PRIMARY KEY,
      movie_name TEXT,
      theatre_name TEXT,
      price TEXT
    );