# identity pod (in apollo-airlines-apps) can reach identity-db on 5432.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-identity-app-to-identity-db
  namespace: apollo-airlines-apps
spec:
  podSelector:
    matchLabels:
      app: identity-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: apollo-airlines-apps
          podSelector:
            matchLabels:
              app: identity
      ports:
        - protocol: TCP
          port: 5432
