apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: apollo11
  name: moviedb
  labels:
    app: moviedb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi