apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-db-init-script
  namespace: apollo-airlines-apps
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    CREATE TABLE IF NOT EXISTS bookings (
        id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        booking_reference VARCHAR(20) UNIQUE NOT NULL,
        user_id           UUID NOT NULL,
        flight_id         UUID NOT NULL,
        seat_number       VARCHAR(10),
        status            VARCHAR(20) DEFAULT 'CONFIRMED',
        created_at        TIMESTAMP DEFAULT NOW(),
        updated_at        TIMESTAMP DEFAULT NOW()
    );
