apiVersion: v1
kind: Service
metadata:
  name: notification-redis-headless
  namespace: apollo11-infra
spec:
  clusterIP: None
  selector:
    app: notification-redis
  ports:
    - port: 6380
      targetPort: 6380
