apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flight-db-allow-apps
  namespace: apollo11-infra
spec:
  podSelector:
    matchLabels:
      app: flight-db
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: apollo11-apps
      ports:
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress