apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apollo11-admin
  namespace: apollo11-apps
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]