apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: apollo11
  name: theatredb
  labels:
    app: theatredb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi