apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: theatredb
  namespace: apollo11
spec:
  selector:
    matchLabels:
      app: theatredb
  serviceName: "theatredb"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: theatredb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: theatredb
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: theatredb
        volumeMounts:
        - name: theatredb
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: theatredb
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: theatredb
              key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: theatredb
          persistentVolumeClaim:
            claimName: theatredb