apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  namespace: apollo11-apps
  labels:
    app: booking
    stage: "6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
        stage: "6"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: apollo11-apps
      priorityClassName: apollo11-app-critical
      terminationGracePeriodSeconds: 30
      containers:
        - name: booking
          image: apollo11/booking:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:***@booking-db.apollo11-infra.svc.cluster.local:5432/booking"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: apollo11-secrets
                  key: JWT_SECRET
            - name: FLIGHT_SERVICE_URL
              value: "http://flight.apollo11-apps.svc.cluster.local:8081"
            - name: IDENTITY_SERVICE_URL
              value: "http://identity.apollo11-apps.svc.cluster.local:8080"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification.apollo11-apps.svc.cluster.local:8084"
            - name: PORT
              value: "8082"
          envFrom:
            - configMapRef:
                name: apollo11-config
          startupProbe:
            httpGet:
              path: /healthz/startup
              port: 8082
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi