{{- if .Values.priorityClasses.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: apollo-airlines-app-critical
  labels:
    {{- include "apollo11.labels" . | nindent 4 }}
value: 1000000
globalDefault: false
description: "Apollo Airlines app-critical pods (booking, search)."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: apollo-airlines-app-low
  labels:
    {{- include "apollo11.labels" . | nindent 4 }}
value: -100000
globalDefault: false
description: "Apollo Airlines app-low pods (notification)."
{{- end }}
