apiVersion: v1
kind: Service
metadata:
  labels:
    app: timeline-mongodb
  name: timeline-mongodb
  namespace: apollo11
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: timeline-mongodb
