apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-monitor
  namespace: apollo11-infra
  labels:
    app: notification
spec:
  selector:
    matchLabels:
      app: notification
  endpoints:
    - port: 8084
      path: /metrics
      interval: 15s