apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-monitor
  namespace: apollo11-infra
  labels:
    app: search
spec:
  selector:
    matchLabels:
      app: search
  endpoints:
    - port: 8083
      path: /metrics
      interval: 15s