apiVersion: batch/v1
kind: Job
metadata:
  name: init-catalog-db
  namespace: apollo11-apps
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: init-catalog-db
    spec:
      containers:
        - name: init
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h catalog-postgres.apollo11-infra.svc.cluster.local -U postgres; do
                echo "Waiting for catalog-postgres..."
                sleep 2
              done

              psql -h catalog-postgres.apollo11-infra.svc.cluster.local -U postgres -d catalog -f /init/init.sql || true
              echo "catalog DB init done"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: apollo11-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /init
      volumes:
        - name: init-script
          configMap:
            name: catalog-init-script
      restartPolicy: OnFailure
