apiVersion: v1
kind: ServiceAccount
metadata:
  name: apollo11-infra
  namespace: apollo11-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apollo11-apps
  namespace: apollo11-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apollo11-ui
  namespace: apollo11-ui