apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telemetry-app
  name: telemetry-app
  namespace: apollo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-app
  template:
    metadata:
      labels:
        app: telemetry-app
    spec:
      nodeName: apollo-worker2
      containers:
      - image: liftoff-telemetry-app
        name: liftoff-telemetry-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: telemetry-app
        env:
        - name: DB_HOST
          value: "telemetry-postgres.apollo11.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "telemetry"

          