apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-postgres
  namespace: apollo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-postgres
  template:
    metadata:
      labels:
        app: catalog-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apollo11-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "catalog"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          emptyDir: {}