apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-postgres-dep.yaml
  - auth-postgres-svc.yaml
  - catalog-postgres-dep.yaml
  - catalog-postgres-svc.yaml
  - circulation-postgres-dep.yaml
  - circulation-postgres-svc.yaml
