apiVersion: v1
kind: Service
metadata:
  name: paymentdb
  namespace: apollo11
  labels:
    app: paymentdb
spec:
  ports:
  - port: 3306
    name: paymentdb
  clusterIP: None
  selector:
    app: paymentdb