apiVersion: v1
kind: Secret
metadata:
  name: apollo11-secrets
  namespace: apollo11-infra
type: Opaque
stringData:
  POSTGRES_PASSWORD: "apollo11_prod_password"
  JWT_SECRET: "apollo11_jwt_secret_key_production_2024"
  API_KEY: "apollo11_api_key_production"
