apiVersion: v1
kind: Service
metadata:
  name: bookingdb
  namespace: apollo11
  labels:
    app: bookingdb
spec:
  ports:
  - port: 5432
    name: bookingdb
  clusterIP: None
  selector:
    app: bookingdb