apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookingdb
  namespace: apollo11
  labels:
    app: bookingdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi