apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: booking-db-allow-apps
  namespace: apollo-airlines-infra
spec:
  podSelector:
    matchLabels:
      app: booking-db
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: apollo-airlines
              app.kubernetes.io/component: apps
      ports:
        - protocol: TCP
          port: 5432
  policyTypes:
    - Ingress