apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  labels:
    app: movie
  name: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
        - image: <private gcr repo>/apollo11-movie/movie@sha256:ef1385fdce793c6ac30045ae63f8c82e8fc2bac4aa6bf147f47bcb40db932895
          name: movie
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /started
              port: 8000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            successThreshold: 5
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: movie
                  key: MONGO_URL
            - name: THEATRE_URL
              valueFrom:
                configMapKeyRef:
                  name: movie
                  key: THEATRE_URL
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie
                  key: MONGO_PASSWORD
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: movie
                  key: MONGO_PORT
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: movie
                  key: MONGO_USER
            - name: THEATRE_PORT
              valueFrom:
                secretKeyRef:
                  name: movie
                  key: THEATRE_PORT
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
