apiVersion: batch/v1
kind: Job
metadata:
  name: init-booking-db
  namespace: apollo-airlines
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: init-booking-db
    spec:
      containers:
        - name: init
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h booking-db -U postgres; do echo "Waiting for booking-db..."; sleep 2; done
              psql -h booking-db -U postgres -d booking -f /init/init.sql || true
              echo "booking DB init done"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: apollo-airlines-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /init
      volumes:
        - name: init-script
          configMap:
            name: booking-init-script
      restartPolicy: OnFailure