apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identity-init-configmap.yaml
  - init-identity-db.yaml
  - flight-init-configmap.yaml
  - init-flight-db.yaml
  - booking-init-configmap.yaml
  - init-booking-db.yaml
