apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  labels:
    app: theatre
  name: theatre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: theatre
  template:
    metadata:
      labels:
        app: theatre
    spec:
      containers:
        - image: apollo11-theatre:latest
          name: theatre
          imagePullPolicy: Never
          startupProbe:
            httpGet:
              path: /started
              port: 7000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 7000
            initialDelaySeconds: 30
            successThreshold: 5
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 7000
            initialDelaySeconds: 30
            terminationGracePeriodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: theatre
                  key: MONGO_URL
            - name: MONGO_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: theatre
                  key: MONGO_AUTH_DB
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: theatre
                  key: MONGO_PASSWORD
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: theatre
                  key: MONGO_PORT
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: theatre
                  key: MONGO_USER
          ports:
            - containerPort: 7000
              protocol: TCP
      restartPolicy: Always
