apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: command-dispatcher
  name: command-dispatcher
  namespace: apollo11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-dispatcher
  template:
    metadata:
      labels:
        app: command-dispatcher
    spec:
      containers:
      - image: liftoff-command-dispatcher
        name: liftoff-command-dispatcher
        imagePullPolicy: Never
        env:
        - name: LUNAR_MODULE_URL
          value: "http://lunar-app:8080/command"
        ports:
        - containerPort: 8000
          name: timeline-command-dispatcher
